### ISSUE TITLE
Doesn't work if a source file has an extension

### ISSUE THREAD

**Issue by nvandamme** [Zoltu/typescript-transformer-append-js-extension#16] opened 2022-03-16 21:28 UTC
https://github.com/Zoltu/typescript-transformer-append-js-extension/blob/3df3f7885bd1c96337c72974f44dbba017cf9097/source/index.ts#L27

For example, if my sources files has some existing extension like *.models *.tests ...

Quick fix : 

```ts
if (['.js', '.mjs', '.cjs', '.json'].includes(path.extname(node.moduleSpecifier.text)) === true) return false
```

**Comment by MicahZoltu** [comment] 2022-03-17 11:58
Duplicate of #9, which is currently "won't fix"/"out of scope".  I recommend reading through the discussion there, but the TL;DR is that for this project I chose to go with the absolute simplest solution that solved what I believe to be the most common use case, and I don't believe it is worth adding complexity to this very simple project to extend support to a small number of additional use cases.

As I mention in that other issue, I **strongly** support people forking this repository and adding features like this, and if you maintain such a fork I would be happy to link to it in the readme.  I believe I give instructions in #9 on how one can very easily fork and publish this under a different name but with tiny changes like this added.

**Closed as completed by MicahZoltu** 2022-03-17 11:58 UTC

**Comment by nvandamme** [comment] 2022-03-17 12:04
Ok, thanks

**Comment by nvandamme** [comment] 2022-03-17 18:41
Here you go with a fork : https://github.com/nvandamme/typescript-transformer-append-js-extension

**Comment by MicahZoltu** [comment] 2022-03-18 07:14
Submitted a PR to your readme to fix it up, and also linked to your project here: https://github.com/Zoltu/typescript-transformer-append-js-extension/blob/master/README.md#note
