### ISSUE TITLE
transform doesn't work for nested extension

### ISSUE THREAD

**Issue by webberwang** [Zoltu/typescript-transformer-append-js-extension#10] opened 2020-04-13 15:10 UTC
names like `foo.module` won't resolve correctly

Compile results

```js
import { foo } from './foo.module';
import { bar } from './bar.js';
import { baz } from "./.baz/index.js";
export { foo } from "./foo.module";
export { bar } from "./bar.js";
export { baz };
export { Banana } from "./multiple-types.js";
foo();
bar();
baz();
```

<img width="475" alt="typescript-transformer-append-js-extension____Code_Clones_typescript-transformer-append-js-extension__-_____tests_output_index_js" src="https://user-images.githubusercontent.com/26264925/79131856-2470ee00-7d5e-11ea-8379-51380d0bffdc.png">

**Comment by MicahZoltu** [comment] 2020-04-13 15:42
This is a known issue.  The tradeoff being made in this project is to do the *wrong* thing for files with a `.` in the name portion of the file name (before the extension) and in exchange ensure that it always does the *right* thing when there is an extension present, regardless of the length of that extension.

That is to say, this project doesn't assume that `.module` isn't an extension just because it is long, and the project will not add extensions if one is already present.  For example, if you do `import 'apple.css'` it should not rewrite that to `import 'apple.css.js'`.

If you wanted to fork this project to always add the `.js` extension (certainly not an unreasonable desire), you would simply need to remove these two lines:
https://github.com/Zoltu/typescript-transformer-append-js-extension/blob/3df3f7885bd1c96337c72974f44dbba017cf9097/source/index.ts#L26-L27

It has been suggested in the past to add some configuration mechanism, but the code required to add a configuration system would be vastly larger and more complicated than the transformer itself, which is why I have chosen not to add a config to this project.

If you do fork this project and publish it with those lines removed, let me know and I'll link to your project in the readme!

**Comment by MicahZoltu** [comment] 2020-04-20 01:27
Marking this as closed - by design.  Let me know if you have further questions!

**Closed as completed by MicahZoltu** 2020-04-20 01:27 UTC
