### ISSUE TITLE
Plugin prevents stripping interfaces and types from imports

### ISSUE THREAD

**Issue by digulla** [Zoltu/typescript-transformer-append-js-extension#3] opened 2019-08-12 15:01 UTC
I have a module A which exports classes, types and interfaces:

    export class Event {
    	// empty
    }
    
    export interface EventHandler {
    	handle(event: Event): void
    }
    
    export type EventCallback = (event: Event) => void

I can use this in another module B:

    import {
    	EventCallback,
    	EventHandler,
    	Event
    } from "./ts_interface_bug"
    
    let x: EventCallback = (event) => {
    	console.log(event)
    }
    
    class MyHandler implements EventHandler {
    	handle(event: Event): void {
    	console.log(event)
    	}
    }

but the compiler keeps the types when generating JavaScript (`B.js`):

    import { EventCallback, EventHandler, Event } from "./ts_interface_bug.js";
    let x = (event) => {
        console.log(event);
    };
    class MyHandler {
        handle(event) {
            console.log(event);
        }
    }

This is wrong - no code is generated for types and interfaces as you can see in `A.js`:

    export class Event {
    }

so the import should look like so:

    import { Event } from "./ts_interface_bug.js";

I think this is a bug in the transformation or ttypescript because it works with pure `tsc`

TypeScript 3.5.3

`tsconfig-build.json`:

    "compilerOptions": {
        "allowJs": true,
        "noImplicitAny": true,
        "removeComments": true,
        "preserveConstEnums": true,
        "sourceMap": true,
        "strict": true,
        "strictPropertyInitialization": false,
        "target": "ES2016",
        "lib": [
    		"dom", "ES2016"
        ],
        "module": "ES2015",
        "moduleResolution": "node",
        "typeRoots": [
            "./node_modules/@types"
        ],
        "plugins": [
            {
                "transform": "@zoltu/typescript-transformer-append-js-extension/output/index.js"
            }
        ],
    },

`package.json`:

    "scripts": {
        "build": "ttsc --build tsconfig-build.json",
    },
    "devDependencies": {
      "@zoltu/typescript-transformer-append-js-extension": "^1.0.1",
      "ttypescript": "^1.5.7",
      "typescript": "^3.5.3"
    }

**Comment by MicahZoltu** [comment] 2019-08-12 18:15
Hmm, that is surprising.  It probably means I am not properly telling TSC to continue with processing of the line before/after my transformation.  Unfortunately, the transformation API is largely undocumented, so I'm not sure what I'm doing wrong.  Tomorrow I'll try to create a test case and see if I can figure out where the issue is, but no promises.

If you can figure out where the bug is, I would be happy to fix it!

**Comment by MicahZoltu** [comment] 2019-08-13 12:49
I haven't resolved this yet, but the source of the problem is here:
https://github.com/microsoft/TypeScript/blob/05af8faac627017166752e14d9b0ad050cea4d53/src/compiler/transformers/ts.ts#L243-L244
> If the node has been transformed by a `before` transformer, perform no ellision on it as the type information we would attempt to lookup to perform ellision is potentially unavailable for the synthesized nodes

**Comment by MicahZoltu** [comment] 2019-08-13 13:03
@digulla I figured out how to resolve the issue.  When setting this transformer up, you should set the `"after": true` flag:
```json
{
	"compilerOptions": {
		"module": "es2015",
		"plugins": [
			{ "transform": "@zoltu/typescript-transformer-append-js-extension/output/index.js", "after": true }
		]
	},
}
```

This will cause this transformer to run after all of the other transformers have run, which includes the transformer that visits the files referenced and figures out what the types being imported/exported are.  If it is run before them (the default with ttypescript) then the code mentioned in the previous comment will get hit which results in not visiting the source file, thus not resolving the imported types, thus not being able to filter out types that shouldn't be emitted.

**Closed as completed** 2019-08-13 13:10 UTC

**Comment by digulla** [comment] 2019-08-13 15:02
+1 for the quick fix!
Just one suggestion: Format the code in the example in the README like this:

	"plugins": [
		{
			"transform": "@zoltu/typescript-transformer-append-js-extension/output/index.js",
			"after": true
		}
	]

Otherwise, the "after" is easily lost.

**Comment by MicahZoltu** [comment] 2019-08-14 06:00
Made the suggested change to the readme.  For what it is worth, I added the `"after": true` to the readme after troubleshooting this issue, so you didn't miss it the first time around.  :)
